### ISSUE TITLE
Maschine MK1 problems

### ISSUE THREAD

**Issue by hokkaido** [shaduzlabs/cabl#10]
First off, thank you for the time and effort you put into this project!

I built this project on a raspberry pi and tried both `master` and `develop`. I also hooked up the Maschine MK1 both directly and through a powered hub to the raspberry pi.

The `device-test` is able to list my Maschine MK1, however immediately after connecting it fails to make any writes or reads and is stuck in an error loop.

Do you have any pointers on how I could fix this? Thanks a lot.

```[MaschineMK1] read: ERROR
[MaschineMK1] tick: error in step #1 (read)
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=16
[DeviceHandleLibUSB] write: error=-1 - transfer size: 33 written: 0
[MaschineMK1] sendLeds: error writing first block of leds
[MaschineMK1] tick: error in step #2 (sendLeds)```

**Comment by shaduzlabs** [comment]
Thanks Fabio! 
One question: did you try to run the executable with root privileges via `sudo`? Unless you modified the default `udev` rules configuration, you won't be able to access the usb device.

**Comment by hokkaido** [comment]
Thanks for the answer. Yes, I tried it with root privileges...

**Comment by shaduzlabs** [comment]
Alright, I'll borrow a Maschine MK1 in the next days and will try to reproduce it. Will keep you posted!

**Comment by shaduzlabs** [comment]
Ok, I found the issue:
```T:  Bus=01 Lev=02 Prnt=02 Port=01 Cnt=02 Dev#=  4 Spd=480 MxCh= 0
D:  Ver= 2.00 Cls=ff(vend.) Sub=ff Prot=ff MxPS=64 #Cfgs=  1
P:  Vendor=17cc ProdID=0808 Rev=00.0d
S:  Manufacturer=Native Instruments
S:  Product=Maschine Controller
S:  SerialNumber=XXXXXXXXXXX
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=280mA
I:  If#= 0 Alt= 1 #EPs= 4 Cls=ff(vend.) Sub=ff Prot=00 Driver=snd-usb-caiaq
```

The driver `snd-usb-caiaq` is already claiming the interface, I guess that's also what happens on your system (you can verify it by running `usb-devices`).
The fix is quite easy, I'll commit it tonight to `develop`.

cheers!

**Comment by shaduzlabs** [comment]
@hokkaido I just committed a fix to `develop`, I've quickly tested it locally on a rpi3 and it seems to work now, let me know if it works for you as well.

**Comment by hokkaido** [comment]
Hey @shaduzlabs - I've just pulled from `develop` and rebuilt the library, it works! Thanks a ton!

**Comment by fzero** [comment]
@hokkaido You should probably close this issue. Also: look at that, another Fabio!
