### ISSUE TITLE
Build error on develop branch

### ISSUE THREAD

**Issue by fzero** [shaduzlabs/cabl#15]
Hi there! First of all, thanks for taking the time to build this library! I started a similar project recently and your code helps a lot.

I have a Machine MK1 and I ran into the problem described on [issue 10](https://github.com/shaduzlabs/cabl/issues/10) when compiling the library from `master`. The test apps work fine if I `rmmod snd-usb-caiaq` first, but that's not ideal - especially considering I also have an Audio2 DJ that I plan to use in my project.

So I tried to compile the library again from `develop`, but it looks like `unmidify` is missing from this branch. It looks like a makefile problem, since `unmidify` is downloaded and compiled just fine on `master`, but I'm hardly an expert!

Here's the `make` output:
```sh
pi@pi ~/.../build(develop)$ make
Scanning dependencies of target cabl-static
[  0%] Building CXX object CMakeFiles/cabl-static.dir/src/client/Client.cpp.o
In file included from /home/pi/Code/cabl/src/devices/ableton/Push2.h:14:0,
                 from /home/pi/Code/cabl/src/client/Client.cpp:10:
/home/pi/Code/cabl/src/devices/generic/USBMidi.h:11:24: fatal error: unmidify.hpp: No such file or directory
 #include <unmidify.hpp>
                        ^
compilation terminated.
CMakeFiles/cabl-static.dir/build.make:62: recipe for target 'CMakeFiles/cabl-static.dir/src/client/Client.cpp.o' failed
make[2]: *** [CMakeFiles/cabl-static.dir/src/client/Client.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cabl-static.dir/all' failed
make[1]: *** [CMakeFiles/cabl-static.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by quasart** [comment]
Did you load submodules ?

`git submodule update --init --recursive`

(Readme file has changed in dev branch.)

**Comment by fzero** [comment]
My bad, I skipped the README. Build went just fine now and I'll test it properly when I get home. Thanks!
