### ISSUE TITLE
libusb: warning [darwin_transfer_status] transfer error: timed out

### ISSUE THREAD

**Issue by metasyn** [shaduzlabs/cabl#2]
hey! awesome project. stoked to have found it after reading your blog posts.

I compiled & everything seems fine - the buttons work, the pads are lighting. Euklid looks really fun, but for some reason I can't hear anything.

It it looks like I keep getting this error in the terminal:

```
libusb: warning [darwin_transfer_status] transfer error: timed out
```

As the error implies, I'm on OSX, specifically 10.11. Anyhow, just out curiosity, if you know how to proceed, do tell, otherwise, thanks for the entertainment regardless.

**Comment by shaduzlabs** [comment]
Hi! Glad you appreciate the library :) 
Not sure it's still relevant, anyways: Euklid is a midi-only app, on OS X it will also generate a virtual MIDI port and the sequencer events will be sent there. The warning shouldn't affect the behavior of the demo application.
