### ISSUE TITLE
case-sensitive CoreMIDI error in DeviceTest

### ISSUE THREAD

**Issue by aspanoz** [shaduzlabs/cabl#5]
OSX 10.12
I got an error on building  DeviceTest

    ld: framework not found CoreMidi
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [examples/DeviceTest/device-test] Error 1
    make[1]: *** [examples/DeviceTest/CMakeFiles/device-test.dir/all] Error 2
    make: *** [all] Error 2

I have case-sensitive hard drive. To fix this, I rename `CoreMidi` to `CoreMIDI`.

https://github.com/shaduzlabs/cabl/blob/23f13a366ca91882d08f70c7d10436d043a6ed13/examples/device-test/CMakeLists.txt#L51

**Comment by shaduzlabs** [comment]
Just pushed a fix to develop, thanks for the heads up!
