### ISSUE TITLE
MK2, shiftPressed in keyChanged always false

### ISSUE THREAD

**Issue by aspanoz** [shaduzlabs/cabl#6]
OSX 10.12, NI Maschine MKII

I have found bug:  I press pad with shift button or without shift there is no difference. `keyChanged` always get false in `shiftPressed`. `buttonChanged` and `encoderChanged` work fine with shift button.

For test I had to modify `DeviceTest.cpp` example.

    void DeviceTest::buttonChanged(Device::Button button_, bool buttonState_, bool shiftState_)
    {
      std::string value = "Butt#" + std::to_string(static_cast<int>(button_)) + (shiftState_ ? " SHIFT" : "");
      device()->setButtonLed(
        button_, buttonState_ ? (shiftState_ ? kColor_Red : kColor_Yellow) : kColor_Black);

      device()->graphicDisplay(0)->black();
      device()->graphicDisplay(0)->putText(10, 10, value.c_str(), {0xff});
    }

    //--------------------------------------------------------------------------------------------------

    void DeviceTest::encoderChanged(unsigned encoder_, bool valueIncreased_, bool shiftPressed_)
    {
      std::string value = "Enc#" + std::to_string(static_cast<int>(encoder_)) + ( valueIncreased_ ? " increased" : " decreased" ) + (shiftPressed_ ? " SHIFT" : "");
      device()->textDisplay(0)->putText(value.c_str(), 0);

      device()->graphicDisplay(0)->black();
      device()->graphicDisplay(0)->putText(10, 10, value.c_str(), {0xff});

    }

    //--------------------------------------------------------------------------------------------------

    void DeviceTest::keyChanged(unsigned index_, double value_, bool shiftPressed_)
    {
      std::string value = "Pad#" + std::to_string(static_cast<int>(value_ * 0xff)) + (shiftPressed_ ? " SHIFT" : "");
      device()->setKeyLed(index_, {static_cast<uint8_t>(value_ * 0xff)});

      device()->graphicDisplay(0)->black();
      device()->graphicDisplay(0)->putText(10, 10, value.c_str(), {0xff});
    }

**Comment by shaduzlabs** [comment]
Many thanks! This bug was affecting all of the NI controllers, should be fixed now on **develop**, could you please verify it and close the issue if this is the case?

**Comment by aspanoz** [comment]
Thanks for hotfix! You do epic work!
