### ISSUE TITLE
Update README.md, add git modules derectives

### ISSUE THREAD

**Issue by aspanoz** [shaduzlabs/cabl#7]
Maybe it a good idea add some help for git newbie and add command for git submodules. I'm talking about part where you say how to clone repository. Something like that:

    git clone https://github.com/shaduzlabs/cabl.git
    cd cabl
    git submodule init
    git submodule update
    mkdir build && cd build

**Comment by shaduzlabs** [comment]
that's already included in the _develop_ branch, which will hopefully be merged to _master_ within a couple of weeks :)

**Comment by aspanoz** [comment]
Oh! My mistake :)
